# Generated by Django 3.0.6 on 2020-05-20 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200520_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='datetime',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='savedby',
            new_name='saved_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qnans', to='questions.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
