# Generated by Django 3.0.6 on 2020-05-21 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200520_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvotedans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvotedans', to=settings.AUTH_USER_MODEL),
        ),
    ]
